# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: magerecord 0.5.2 ruby lib

Gem::Specification.new do |s|
  s.name = "magerecord".freeze
  s.version = "0.5.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Marc".freeze]
  s.date = "2018-11-19"
  s.description = "A simple ActiveRecord wrapper for various Magento models".freeze
  s.email = "xerokill@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/magerecord.rb",
    "lib/magerecord/address.rb",
    "lib/magerecord/connection.rb",
    "lib/magerecord/coupon.rb",
    "lib/magerecord/customer.rb",
    "lib/magerecord/eav_record.rb",
    "lib/magerecord/fitlion/club.rb",
    "lib/magerecord/fitlion/ff_order.rb",
    "lib/magerecord/fitlion/order.rb",
    "lib/magerecord/fitlion/order_payment.rb",
    "lib/magerecord/fitlion/product.rb",
    "lib/magerecord/fitlion/trainer.rb",
    "lib/magerecord/invoice_item.rb",
    "lib/magerecord/order.rb",
    "lib/magerecord/order_address.rb",
    "lib/magerecord/order_history.rb",
    "lib/magerecord/order_item.rb",
    "lib/magerecord/order_payment.rb",
    "lib/magerecord/product.rb",
    "lib/magerecord/product_attribute_set.rb",
    "lib/magerecord/stock.rb",
    "lib/magerecord/store.rb",
    "lib/magerecord/website.rb",
    "magerecord.gemspec",
    "test/helper.rb",
    "test/test_magerecord.rb"
  ]
  s.homepage = "http://github.com/mystix/magerecord".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.6".freeze
  s.summary = "Simple ActiveRecord wrapper for Magento".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>.freeze, [">= 4.1"])
      s.add_runtime_dependency(%q<mysql2>.freeze, [">= 0.4.0"])
      s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, [">= 3.0"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.13"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 2.0.1"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    else
      s.add_dependency(%q<activerecord>.freeze, [">= 4.1"])
      s.add_dependency(%q<mysql2>.freeze, [">= 0.4.0"])
      s.add_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, [">= 3.0"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.13"])
      s.add_dependency(%q<jeweler>.freeze, [">= 2.0.1"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>.freeze, [">= 4.1"])
    s.add_dependency(%q<mysql2>.freeze, [">= 0.4.0"])
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, [">= 3.0"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.13"])
    s.add_dependency(%q<jeweler>.freeze, [">= 2.0.1"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

